### ISSUE TITLE
Spanish translation latest WPKG-GP-Client.pot

### ISSUE THREAD

**Issue by Jsantolin** [sonicnkt/wpkg-gp-client#2]
[es_ES.zip](https://github.com/sonicnkt/wpkg-gp-client/files/488016/es_ES.zip)

**Comment by sonicnkt** [comment]
Thank you very much, will be integrated in the next version!

**Comment by sonicnkt** [comment]
I just added your translation but i had to change the translation base a little bit again :(
Sorry for bothering you again but hope you can translate the new added string. Thanks!
